[supabase]
url = "https://ochoefiwveizzrgvklip.supabase.co"
service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jaG9lZml3dmVpenpyZ3ZrbGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyOTg1NDQsImV4cCI6MjA3OTg3NDU0NH0.8h8IGqBUA641blZTzSIuOVBw4Hjh8NbH6fIuK7Ab--g"



SUPABASE_URL = "https://ochoefiwveizzrgvklip.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jaG9lZml3dmVpenpyZ3ZrbGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyOTg1NDQsImV4cCI6MjA3OTg3NDU0NH0.8h8IGqBUA641blZTzSIuOVBw4Hjh8NbH6fIuK7Ab--g"